version: "3.12-slim"

volumes:
  orderapp:

services:
  order-service:
    container_name: order-service-container
    build:
      context: .
    ports:
      - "5001:5001"
    volumes:
      - orderapp:/orderapp
    restart: always
